# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('estatus',),
                'verbose_name_plural': 'Calidad de los Servicios',
                'verbose_name': 'Calidad del Servicio',
            },
        ),
        migrations.CreateModel(
            name='ComiteUnidadEjecutiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('tipo',),
                'verbose_name_plural': 'Comites del consjo comunal',
                'verbose_name': 'Comite del Consejo Comunal',
            },
        ),
        migrations.CreateModel(
            name='CondicionVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condiciones', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('condiciones',),
                'verbose_name_plural': 'Condiciones de las Viviendas',
                'verbose_name': 'Condicion de la Vivienda',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civiles', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('estado_civiles',),
                'verbose_name_plural': 'Estado Civil',
                'verbose_name': 'Estado Civil',
            },
        ),
        migrations.CreateModel(
            name='EstadoVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('estado',),
                'verbose_name_plural': 'Estados de las Viviendas',
                'verbose_name': 'Estado de la Vivienda',
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nacionalidades', models.CharField(max_length=128)),
                ('fk_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Pais', verbose_name='Pais')),
            ],
            options={
                'ordering': ('tipo_nacionalidades',),
                'verbose_name_plural': 'Nacionalidades',
                'verbose_name': 'Nacionalidad',
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentescos', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('parentescos',),
            },
        ),
        migrations.CreateModel(
            name='TipoEnfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_enfermedades', models.CharField(max_length=500, unique=True)),
                ('causa', models.TextField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('tipo_enfermedades',),
                'verbose_name_plural': 'Tipo Enfermedades',
                'verbose_name': 'Tipo Enfermedad',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('tipos',),
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajos', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ('tipo_trabajos',),
                'verbose_name_plural': 'Tipos de Trabajo',
                'verbose_name': 'Tipo Trabajo',
            },
        ),
        migrations.CreateModel(
            name='UnidadesConsejoComunal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('tipo',),
                'verbose_name_plural': 'Unidades de los Consejos Comunales',
                'verbose_name': 'Unidad del Consejo Comunal',
            },
        ),
        migrations.AddField(
            model_name='comiteunidadejecutiva',
            name='fk_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.UnidadesConsejoComunal', verbose_name='Unidad Ejecutiva'),
        ),
    ]
